# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: U6OeojbyJecFjbZ6bTToukyeXvz0ucR9
            client-secret: e8T_8dHxLKF44Kx4BzMLHn9R-2D4xQC2tg1se12D7I7MF1Vw_CLb5nZOxjnZv3YH
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-wlc8lulk.us.auth0.com/